config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#index'
  resources :pages, only: %i[index]
  resources :users do
    resources :categories do
      resources :purchases
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)

    can :manage, Category, user_id: user.id
    can :manage, Purchase, user_id: user.id
    can :read, :all

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, dependent: :destroy
  has_many :purchases

  validates :name, presence: true, length: { maximum: 50 }
  validates :icon, presence: true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :author, class_name: 'User', dependent: :destroy
  belongs_to :category, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, dependent: :destroy
  has_many :purchases, foreign_key: :author_id, dependent: :destroy

  validates :name, presence: true, length: { maximum: 250, minimum: 3 }
  validates :email, presence: true, length: { maximum: 250 }
  validates_uniqueness_of :email, case_sensitive: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    [current_user, :categories]
  end

  def after_sign_out_path_for(_resource_or_scope)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = current_user.categories
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.new(category_params)
    if @category.save
      flash.notice = 'Category was successfully created.'
      redirect_to user_categories_path
    else
      flash.alert = 'Category was not created.'
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def index
    @user = current_user
    @category = Category.find(params[:category_id])
    @purchases = @category.purchases.order(created_at: :desc)
  end

  def new
    @category = Category.find(params[:category_id])
  end

  def create
    @category = Category.find(params[:category_id])
    @purchase = @category.purchases.new(purchase_params)

    if @purchase.save
      flash.notice = 'Purchase was successfully created.'
      redirect_to user_category_purchases_path(params[:user_id], params[:category_id])
    else
      flash.alert = 'Purchase was not created.'
      render :new
    end
  end

  private

  def purchase_params
    params.require(:purchase).permit(:author_id, :category_id, :name, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_categories.html.erb
<% categories.each do |c| %>
    <div class="list-group list-group-light m-2 card">
        <a href="<%= user_category_purchases_path(user_id: current_user.id, category_id: c.id) %>"  class="list-group-item list-group-item-action ">
            <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center w-100">
                    <%= image_tag c.icon, size: "85x85"%>
                    <div class="m-3 flex-grow-1">
                        <p class="fw-bold mb-1"><%= c.name%></p>
                        <hr class='m-0 w-100'/>
                        <div class="text-muted"><%= c.created_at.strftime('%a-%b-%Y')%></div>
                    </div>
                </div>
                <span><b>
                <% total = 0 %>
                <% c.purchases.each do |p|%>
                    <%total += p.amount%>
                <%end%>
                $<%= total%>
                </b></span>
            </div>
        </a>
    </div>
<% end %>

app/views/categories/index.html.erb
<% if user_signed_in? %>  
    <%= render 'shared/navbar' %>
<% end %>

<div class="d-flex align-items-center flex-column mb-3 justify-content-around" >
    <% if @categories.length > 0 %>
        <%= render partial: 'categories', locals: {categories: @categories } %>
    <% else %>
        <div style='margin: 40px;'>
            <h4><%= 'No category to display' %></h4>
        </div>
    <% end %>
    <div class="w-100 text-center mb-auto add-category">
        <%= link_to 'ADD CATEGORY', new_user_category_path, class: 'list-group-item list-group-item-action', style: "background-color: #5fb523; color: #fff; border-radius: 5px;" %>    
    </div>
</div>

app/views/categories/new.html.erb
<div class='d-flex justify-content-center align-items-center'>
    <div class='container border border-light rounded py-5 px-3 mx-auto home-page d-flex flex-column align-items-center justify-content-center text-justify'>
        <h2>New Category</h2>
        <%= form_with url: user_categories_path, method: :post, local: true, scope: :category do |f| %>
            <div class="mb-3">
                <%= f.label :name, class: 'form-label' %><br>
                <%= f.text_field :name, class: 'form-control' %>
            </div>
            <div class="mb-3 form-select">
                <%= f.label :icon, class: 'form-label' %><br>
                <%= f.select :icon, [['Select an icon', ''],
                                    ['Shoa supermarket', 'shoa-supermarket.jpg'],
                                    ['Lomyad supermarket', 'lomyad-supermarket.jpg'],
                                    ['Tutto gelato', 'tutto-gelato.jpg'],
                                    ['Roomi burger', 'roomi-burger.png']


                                    ], class: "icon" 
                %>
            </div>
            <div  class="actions">
                <%= f.submit 'Add Category', class: 'btn btn-primary' %>
            </div>
        <%end%>
    </div>
</div>

app/views/categories/show.html.erb
<h1>show</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class='d-flex justify-content-center align-items-center'>
    <div class='container border border-light rounded py-5 px-3 home-page d-flex flex-column align-items-center justify-content-around'>
        <div class='name-container d-flex align-items-center justify-content-center'>
            <h1 class='app-name' >budgetapp</h1>
        </div>
        <div class="mt-auto w-100 text-center mb-3">
            <% unless user_signed_in? %>
                <%= link_to 'LOG IN', new_user_session_path, class: 'list-group-item list-group-item-action active' %> 
                <%= link_to 'SIGN UP', new_user_registration_path, class: 'list-group-item list-group-item-action' %>   
            <% end %>
        </div>
    </div>
</div>

app/views/purchases/_previousLink.html.erb
<%= link_to 'Back', user_categories_path, class: 'previous' %>

app/views/purchases/_purchases.html.erb
<% purchases.each do |p| %>
    <ul class="list-group list-group-light card">
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <div>
                <div class="fw-bold"><%= p.name%></div>
                <div class="text-muted"><%= p.created_at.strftime('%a-%b-%Y')%></div>
            </div>
            <span><b>$<%= p.amount%></b></span>
        </li>
    </ul>
<% end %>

app/views/purchases/index.html.erb
<% if user_signed_in? %>  
    <%= render 'shared/navbar' %>
<% end %>

<div class="d-flex align-items-center flex-column mb-3 justify-content-around" >
    <div class="list-group-item list-group-light m-2 card">
        <div class="d-flex justify-content-between align-items-center">
            <div class="d-flex align-items-center w-100">
                <%= image_tag @category.icon, size: "85x85"%>
                <div class="m-3 flex-grow-1">
                    <p class="fw-bold mb-1"><%= @category.name%></p>
                </div>
            </div>  
        </div>
    </div>
    <% if @purchases.length > 0 %>
        <%= render partial: 'purchases', locals: {purchases: @purchases } %>
    <% else %>
        <div style='margin: 40px;'>
            <h4 class='text-center'><%= 'No purchases for ' %><%= @category.name %></h4>
        </div>
    <% end %>
    <div class="w-100 text-center add-category">
        <%= link_to 'ADD PURCHASE', new_user_category_purchase_path, class: 'list-group-item list-group-item-action', style: "background-color: #5fb523; color: #fff; border-radius: 5px;" %>   
    </div>
</div>

app/views/purchases/new.html.erb
<div class='d-flex justify-content-center align-items-center'>
    <div class='container border border-light rounded py-5 px-3 mx-auto home-page d-flex flex-column align-items-center justify-content-center text-justify'>
        <h2>New Trasaction</h2>
        <%= form_with url: user_category_purchases_path, method: :post, local: true, scope: :purchase do |f| %>
            <%= f.hidden_field :author_id, value: current_user.id %>
            <%= f.hidden_field :category_id, value: @category.id %>

            <div class="mb-3">
                <%= f.label :name, class: 'form-label' %><br>
                <%= f.text_field :name, class: 'form-control' %>
            </div>
            <div class="mb-3">
                <%= f.label :amount, class: 'form-label' %><br>
                <%= f.text_field :amount, class: 'form-control' %>
             </div>
            <div  class="actions">
                <%= f.submit 'Add Transaction', class: 'btn btn-primary' %>
            </div>
        <%end%>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <%= render 'purchases/previousLink'%>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon humberger"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>   
      <li class="nav-item"> 
        <%= link_to 'Categories', [current_user, :categories], class: 'nav-link' %>  
      </li> 
     
      
      <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
    
    <% end %>
     
    </ul>
  </div>
</nav>